# Generated by Django 5.1.3 on 2024-11-25 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_categorybike_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybike',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bik', to='bike.bike', verbose_name='Товар'),
        ),
    ]
